const app = {
  INCREMENT_COUNTER: 'INCREMENT_COUNTER',
};

const todos = {
  GET_TODOS_REQUEST: 'GET_TODOS_REQUEST',
  GET_TODOS_SUCCESS: 'GET_TODOS_SUCCESS',
  GET_TODOS_FAILURE: 'GET_TODOS_FAILURE',
};

export default {
  app,
  todos,
};
